# Generated by Django 2.1.3 on 2018-12-16 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Video_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_likers',
            field=models.ManyToManyField(related_name='Comment_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='Video_likers',
            field=models.ManyToManyField(related_name='Video_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
